fix directory
sgallagher/baseruntime-package-lists pull request #1
Opened 2017-06-28 18:09 UTC by nathanhan

Added archful folder to rsync path at the end of download_repo.sh

2017-06-28 18:28 UTC, sgallagher requested changes

2017-06-28 18:28 UTC, sgallagher commented on download_repo.sh
> +        override_uri="rsync://fedorapeople.org/project/modularity/repos/fedora/gencore-override/${version_path}/archful/$arch"
You were right that there's a bug here, but 'archful' is the wrong path. You need to replace it with 'override' instead.

2017-06-29 15:09 UTC, nathanhan commented
Path is now "override"

2017-06-29 18:02 UTC, sgallagher approved these changes

2017-06-29 18:03 UTC, merged